version: "3.8"
services:
  promtail:
    image: grafana/promtail:2.8.2
    volumes:
      - /docker/promtail/config.yaml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers