version: "3.8"
services:
  promtail:
    image: grafana/promtail:2.8.3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
    entrypoint:
      - sh
      - -euc
      - |
        cat <<EOF > /etc/promtail/config.yml
        server:
          disable: true

        positions:
          filename: /tmp/positions.yaml

        clients:
          - url: https://loki:${LOKI_PASSWORD}@${LOKI_HOST}/loki/api/v1/push
            external_labels:
              hostname: ${DOCKER_HOSTNAME}

        scrape_configs:
          - job_name: docker-logs
            docker_sd_configs:
              - host: unix:///var/run/docker.sock
                refresh_interval: 5s
            relabel_configs:
              - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
                target_label: 'compose_project'
              - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
                target_label: 'compose_service'
              - source_labels: ['__meta_docker_container_log_stream']
                target_label: 'logstream'
        EOF
        /usr/bin/promtail -config.file=/etc/promtail/config.yml